use_frameworks!

platform :ios, '9.0'

target 'WPlayerKit_Example' do
  pod 'WPlayerKit', :path => '../'

  target 'WPlayerKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
